Output static/img/terminal/dependency-management.gif

Set FontSize 16
Set Width 960
Set Height 540
Set Theme "Dracula"
Set Shell "bash"

Type "freight add fmt@10"
Enter
Sleep 500ms
Type "freight add openssl"
Enter
Sleep 500ms
Type "freight add mathlib --path ../mathlib"
Enter
Sleep 500ms
Type "freight fetch"
Enter
Sleep 600ms
Type "freight tree"
Enter
Sleep 700ms
Type "freight outdated"
Enter
Sleep 700ms
